name: ds_env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.13
  - pip
  - pip:
    - -r requirements/ds_env.txt
#    - -r requirements/another_config_file.txt
#  - run:
#      - ./finish.sh

