#
name: _env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.13
  - pip
  - pip:
# utils
    - notebook
    - pathlib
    - pandas

# main
    -


#    - -r pip_requirements/_env.txt
#    - -r pip_requirements/another_config_file.txt
#  - run:
#      - ./finish.sh


# conda env create --file=./conda_environments/$name_env.yaml
