name: dl_env

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.12
  - pip
  - pip:
    - -r requirements/dl_env.txt
#    - -r requirements/another_config_file.txt
  - run:
      - ./finish.sh

