name: web_env

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.13
  - pip
  - pip:
    - -r ../requirements/web_env.txt
#    - -r requirements/another_config_file.txt
#  - run:
#      - ./finish.sh

